services:

  postgres:
    image: postgres:17
    container_name: pawlink-db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0616"
    ports:
      - "5432:5432"

  app:
    image: pawlink
    container_name: pawlink-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres