spring.application.name=PawLink


# DEBUG
logging.level.org.springframework.web=DEBUG

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=0616
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.flywaydb=DEBUG

# html
spring.thymeleaf.cache=false

# message
spring.messages.basename=messages

# 외부 API
animal.api.key=비공개
animal.api.host=apis.data.go.kr
