spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=0616

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true