--
-- PostgreSQL database dump
--

\restrict WoIsWsCxAiSFiJ5EFZ6DCN9OnUaGf6Qhe7XVqFfHPFVhyFFdRcZhEO4rr5VzvcK

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tb_address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_address (
    id character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    parent_id character varying(255),
    update_date date NOT NULL
);


ALTER TABLE public.tb_address OWNER TO postgres;

--
-- Name: tb_animal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_animal (
    id bigint NOT NULL,
    birth_year character varying(255) NOT NULL,
    breed character varying(255) NOT NULL,
    gender character varying(255),
    missing_adrs1 character varying(255),
    missing_adrs2 character varying(255),
    missing_date date,
    rescued_adrs character varying(255),
    rescued_date character varying(255),
    shelter_id character varying(255),
    species character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    weight character varying(255) NOT NULL,
    CONSTRAINT tb_animal_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying])::text[]))),
    CONSTRAINT tb_animal_species_check CHECK (((species)::text = ANY ((ARRAY['DOG'::character varying, 'CAT'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT tb_animal_status_check CHECK (((status)::text = ANY ((ARRAY['MISSING'::character varying, 'PROTECTING'::character varying, 'ADOPTED'::character varying])::text[])))
);


ALTER TABLE public.tb_animal OWNER TO postgres;

--
-- Name: tb_animal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_animal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_animal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_board_comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_board_comments (
    id bigint NOT NULL,
    board_id bigint NOT NULL,
    board_type character varying(255) NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    guest_password character varying(255),
    guest_user_name character varying(255),
    user_id bigint,
    CONSTRAINT tb_board_comments_board_type_check CHECK (((board_type)::text = ANY ((ARRAY['MISSING_ANIMAL'::character varying, 'RESCUED_ANIMAL'::character varying])::text[])))
);


ALTER TABLE public.tb_board_comments OWNER TO postgres;

--
-- Name: tb_board_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_board_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_board_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_board_missing_animal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_board_missing_animal (
    id bigint NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    title character varying(50) NOT NULL,
    animal_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.tb_board_missing_animal OWNER TO postgres;

--
-- Name: tb_board_missing_animal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_board_missing_animal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_board_missing_animal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_board_rescued_animal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_board_rescued_animal (
    id bigint NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    title character varying(50) NOT NULL,
    desertion_no character varying(255) NOT NULL,
    img_url1 character varying(255),
    img_url2 character varying(255),
    is_valid boolean NOT NULL,
    notice_end_date character varying(255) NOT NULL,
    notice_start_date character varying(255) NOT NULL,
    animal_id bigint NOT NULL,
    shelter_id character varying(255) NOT NULL
);


ALTER TABLE public.tb_board_rescued_animal OWNER TO postgres;

--
-- Name: tb_board_rescued_animal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_board_rescued_animal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_board_rescued_animal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_shelter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_shelter (
    id character varying(255) NOT NULL,
    detail_address character varying(255),
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    tel character varying(255),
    address_id character varying(255) NOT NULL
);


ALTER TABLE public.tb_shelter OWNER TO postgres;

--
-- Name: tb_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_user (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_name character varying(255) NOT NULL,
    shelter_id character varying(255),
    CONSTRAINT tb_user_type_check CHECK (((type)::text = ANY ((ARRAY['NORMAL'::character varying, 'SHELTER'::character varying])::text[])))
);


ALTER TABLE public.tb_user OWNER TO postgres;

--
-- Name: tb_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_address tb_address_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_address
    ADD CONSTRAINT tb_address_pkey PRIMARY KEY (id);


--
-- Name: tb_animal tb_animal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_animal
    ADD CONSTRAINT tb_animal_pkey PRIMARY KEY (id);


--
-- Name: tb_board_comments tb_board_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_comments
    ADD CONSTRAINT tb_board_comments_pkey PRIMARY KEY (id);


--
-- Name: tb_board_missing_animal tb_board_missing_animal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_missing_animal
    ADD CONSTRAINT tb_board_missing_animal_pkey PRIMARY KEY (id);


--
-- Name: tb_board_rescued_animal tb_board_rescued_animal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT tb_board_rescued_animal_pkey PRIMARY KEY (id);


--
-- Name: tb_shelter tb_shelter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_shelter
    ADD CONSTRAINT tb_shelter_pkey PRIMARY KEY (id);


--
-- Name: tb_user tb_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT tb_user_pkey PRIMARY KEY (id);


--
-- Name: tb_board_rescued_animal uk2935mtk5hb2hetf0rk9u8ujon; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT uk2935mtk5hb2hetf0rk9u8ujon UNIQUE (desertion_no);


--
-- Name: tb_board_rescued_animal uk34k2w9nmgl99ua53fnqgffuit; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT uk34k2w9nmgl99ua53fnqgffuit UNIQUE (animal_id);


--
-- Name: tb_board_missing_animal ukd4a12djr76p30uh30scsoblf7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_missing_animal
    ADD CONSTRAINT ukd4a12djr76p30uh30scsoblf7 UNIQUE (animal_id);


--
-- Name: tb_user ukdx61ph83p21e9y80scx92i39p; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT ukdx61ph83p21e9y80scx92i39p UNIQUE (user_name);


--
-- Name: idx_board_comment; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_board_comment ON public.tb_board_comments USING btree (board_type, board_id);


--
-- Name: tb_shelter fk28ctbe8w47srqv439ac3fcex4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_shelter
    ADD CONSTRAINT fk28ctbe8w47srqv439ac3fcex4 FOREIGN KEY (address_id) REFERENCES public.tb_address(id);


--
-- Name: tb_board_comments fka63yhffige1j7qu01x39emrre; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_comments
    ADD CONSTRAINT fka63yhffige1j7qu01x39emrre FOREIGN KEY (user_id) REFERENCES public.tb_user(id);


--
-- Name: tb_board_missing_animal fkkaw4tlnbxf3dr93t3sxsm83gg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_missing_animal
    ADD CONSTRAINT fkkaw4tlnbxf3dr93t3sxsm83gg FOREIGN KEY (user_id) REFERENCES public.tb_user(id);


--
-- Name: tb_user fkl3drhcdg8tspco2ftnogqpjgj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT fkl3drhcdg8tspco2ftnogqpjgj FOREIGN KEY (shelter_id) REFERENCES public.tb_shelter(id);


--
-- Name: tb_board_missing_animal fkplcwre473og9q1abkiwt6w37t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_missing_animal
    ADD CONSTRAINT fkplcwre473og9q1abkiwt6w37t FOREIGN KEY (animal_id) REFERENCES public.tb_animal(id);


--
-- Name: tb_board_rescued_animal fkqj89jucxcjj8fiblh90if213y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT fkqj89jucxcjj8fiblh90if213y FOREIGN KEY (shelter_id) REFERENCES public.tb_shelter(id);


--
-- Name: tb_board_rescued_animal fkt6rs59liqtdwcyesvvppifw8n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT fkt6rs59liqtdwcyesvvppifw8n FOREIGN KEY (animal_id) REFERENCES public.tb_animal(id);


--
-- PostgreSQL database dump complete
--

\unrestrict WoIsWsCxAiSFiJ5EFZ6DCN9OnUaGf6Qhe7XVqFfHPFVhyFFdRcZhEO4rr5VzvcK

