
CREATE TABLE public.tb_address (
    id character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    parent_id character varying(255),
    update_date date NOT NULL
);

CREATE TABLE public.tb_animal (
    id bigint NOT NULL,
    birth_year character varying(255) NOT NULL,
    breed character varying(255) NOT NULL,
    gender character varying(255),
    missing_adrs1 character varying(255),
    missing_adrs2 character varying(255),
    missing_date date,
    rescued_adrs character varying(255),
    rescued_date character varying(255),
    shelter_id character varying(255),
    species character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    weight character varying(255) NOT NULL,
    CONSTRAINT tb_animal_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying])::text[]))),
    CONSTRAINT tb_animal_species_check CHECK (((species)::text = ANY ((ARRAY['DOG'::character varying, 'CAT'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT tb_animal_status_check CHECK (((status)::text = ANY ((ARRAY['MISSING'::character varying, 'PROTECTING'::character varying, 'ADOPTED'::character varying])::text[])))
);

ALTER TABLE public.tb_animal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_animal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tb_board_comments (
    id bigint NOT NULL,
    board_id bigint NOT NULL,
    board_type character varying(255) NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    guest_password character varying(255),
    guest_user_name character varying(255),
    user_id bigint,
    CONSTRAINT tb_board_comments_board_type_check CHECK (((board_type)::text = ANY ((ARRAY['MISSING_ANIMAL'::character varying, 'RESCUED_ANIMAL'::character varying])::text[])))
);

ALTER TABLE public.tb_board_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_board_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tb_board_missing_animal (
    id bigint NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    title character varying(50) NOT NULL,
    animal_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.tb_board_missing_animal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_board_missing_animal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tb_board_rescued_animal (
    id bigint NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    title character varying(50) NOT NULL,
    desertion_no character varying(255) NOT NULL,
    img_url1 character varying(255),
    img_url2 character varying(255),
    is_valid boolean NOT NULL,
    notice_end_date character varying(255) NOT NULL,
    notice_start_date character varying(255) NOT NULL,
    animal_id bigint NOT NULL,
    shelter_id character varying(255) NOT NULL
);

ALTER TABLE public.tb_board_rescued_animal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_board_rescued_animal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tb_shelter (
    id character varying(255) NOT NULL,
    detail_address character varying(255),
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    tel character varying(255),
    address_id character varying(255) NOT NULL
);

CREATE TABLE public.tb_user (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_name character varying(255) NOT NULL,
    shelter_id character varying(255),
    CONSTRAINT tb_user_type_check CHECK (((type)::text = ANY ((ARRAY['NORMAL'::character varying, 'SHELTER'::character varying])::text[])))
);

ALTER TABLE public.tb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tb_address
    ADD CONSTRAINT tb_address_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tb_animal
    ADD CONSTRAINT tb_animal_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tb_board_comments
    ADD CONSTRAINT tb_board_comments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tb_board_missing_animal
    ADD CONSTRAINT tb_board_missing_animal_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT tb_board_rescued_animal_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tb_shelter
    ADD CONSTRAINT tb_shelter_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT tb_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT uk2935mtk5hb2hetf0rk9u8ujon UNIQUE (desertion_no);

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT uk34k2w9nmgl99ua53fnqgffuit UNIQUE (animal_id);

ALTER TABLE ONLY public.tb_board_missing_animal
    ADD CONSTRAINT ukd4a12djr76p30uh30scsoblf7 UNIQUE (animal_id);

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT ukdx61ph83p21e9y80scx92i39p UNIQUE (user_name);

CREATE INDEX idx_board_comment ON public.tb_board_comments USING btree (board_type, board_id);

ALTER TABLE ONLY public.tb_shelter
    ADD CONSTRAINT fk28ctbe8w47srqv439ac3fcex4 FOREIGN KEY (address_id) REFERENCES public.tb_address(id);

ALTER TABLE ONLY public.tb_board_comments
    ADD CONSTRAINT fka63yhffige1j7qu01x39emrre FOREIGN KEY (user_id) REFERENCES public.tb_user(id);

ALTER TABLE ONLY public.tb_board_missing_animal
    ADD CONSTRAINT fkkaw4tlnbxf3dr93t3sxsm83gg FOREIGN KEY (user_id) REFERENCES public.tb_user(id);

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT fkl3drhcdg8tspco2ftnogqpjgj FOREIGN KEY (shelter_id) REFERENCES public.tb_shelter(id);

ALTER TABLE ONLY public.tb_board_missing_animal
    ADD CONSTRAINT fkplcwre473og9q1abkiwt6w37t FOREIGN KEY (animal_id) REFERENCES public.tb_animal(id);

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT fkqj89jucxcjj8fiblh90if213y FOREIGN KEY (shelter_id) REFERENCES public.tb_shelter(id);

ALTER TABLE ONLY public.tb_board_rescued_animal
    ADD CONSTRAINT fkt6rs59liqtdwcyesvvppifw8n FOREIGN KEY (animal_id) REFERENCES public.tb_animal(id);
